# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80470723b24c0c5908babad74310aaa40715334fe4e84d840a1c7de7146f0da305d61df3371d583608974d90ffab61f4d64dd8e68ec0dc2d3dc566c1acc9fa2f

test:
  secret_key_base: fed8cc00425593746707b1b743110f4c9df75b9bed8ffaa7d6192557cfe8cecd2a3764bbb0b03b8d0b217d98315f71c54a277a33c7c59753739832b1683b2b1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
